version: '3.4'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5467:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      retries: 20
      interval: 3s
      start_period: 5s

volumes:
  db_data:
