version: '3.4'

services:
  app:
    container_name: app
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DB__HOST=db
      - DB__PORT=5432

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      retries: 20
      interval: 3s
      start_period: 5s

volumes:
  db_data:
